--DELETE A PATIENT FROM PRESCRITION 1
DELETE FROM prescription
WHERE patient_id ='PN001';
--DELETE A PATIENT FROM PRESCRITION 2
DELETE FROM prescription
WHERE patient_id ='PN002';--2,3
--DELETE A PATIENT FROM PRESCRITION 3
DELETE FROM prescription
WHERE patient_id ='PN003';--2,3