--DELETE A PATIENT FROM CHECKIN 1
DELETE FROM checkin
WHERE patient_id ='PN001';
--DELETE A PATIENT FROM CHECKIN 2
DELETE FROM checkin
WHERE patient_id ='PN002';--2,3
--DELETE A PATIENT FROM CHECKIN  3
DELETE FROM checkin
WHERE patient_id ='PN003';--2,3