--DELETE A PATIENT FROM room 1
DELETE FROM Room
WHERE R_occupied_by ='PN001';
--DELETE A PATIENT FROM room 2
DELETE FROM Room
WHERE R_occupied_by ='PN002';--2,3
--DELETE A PATIENT FROM room  3
--DELETE FROM Room
--WHERE R_occupied_by ='PN003';--2,3